included:
  - HiraganaTranslator
excluded:
  - HiraganaTranslator/generated
  - HiraganaTranslatorTests
  - Pods
  - Carthage
  - vendor

disabled_rules:
  - line_length
  - trailing_whitespace
  - statement_position
  - force_cast

identifier_name:
    excluded:
      - id
      - ok